### ISSUE TITLE
Which library should we use?

### ISSUE THREAD

**Issue by ziadsawalha** [adregner/python-clouddb#1]
This one or https://github.com/slizadel/python-clouddb?

Yours is up to date (thanks for doing that), but it is not compatible with the older one. Are you going to be maintaining this going forward if we port our code to it?

**Comment by adregner** [comment]
I do plan to maintain this for as long as there is interest in it, even if that interest is only my own.  I don't believe either of our projects has been dubbed the "official" bindings, but I hope that at some point in the near future one of ours is so that the best of both can be integrated into one.

I have made some recent updates and fixed, but I would not call mine stable yet.  However with some more test cases and probably a few small patches I will make a 0.7 release, and a 1.0 release once I integrate some more features of the API that I have back-burnered for now.

For what it's worth, mine was started from scratch with the intent of making the most intuitive interface into the API, and I think the other one is just a fork and redactor of the load balances bindings.

**Comment by adregner** [comment]
unless there is additional discussion on this, i'm closing out the issue.

**Comment by ziadsawalha** [comment]
Yep! All good. Thanks.

BTW - there's also the red dwarf client library. My sense is that will be the 'official' one.

Nice work, though. Especially staying up to date with API changes.

Typoed on an autocorrecting mobile device...

**Comment by adregner** [comment]
is the red dwarf client library you are talking about this:

https://github.com/rackspace/reddwarf/tree/reddwarf/master/reddwarfclient

I understand that it is the default client for one's own open stack deployment but i don't see how it is easy/practical to use with rackspace's current implementation of it.

**Comment by ziadsawalha** [comment]
I haven't tried it yet. My code is still running python-clouddb. But that's what the red dwarf team is working on; although I have not heard of them officially supporting it yet.

Typoed on an autocorrecting mobile device...
